# Auto-gerado a partir do tema Omarchy
# Baseado em: alacritty.toml

# Cores básicas
foreground              #cad3f5
background              #24273a
background_opacity      0.9
selection_foreground    #24273a
selection_background    #cad3f5

# Cores do cursor
cursor                  #cad3f5
cursor_text_color       #24273a

# Cor do link URL
url_color               #8aadf4

# Cores das bordas
active_border_color     #8aadf4
inactive_border_color   #494d64
bell_border_color       #eed49f

# Cores das abas
active_tab_foreground   #24273a
active_tab_background   #8aadf4
inactive_tab_foreground #cad3f5
inactive_tab_background #494d64
tab_bar_background      #24273a

# As 16 cores do terminal
# black
color0 #494d64
color8 #494d64

# red
color1 #ed8796
color9 #ed8796

# green
color2  #a6da95
color10 #a6da95

# yellow
color3  #eed49f
color11 #eed49f

# blue
color4  #8aadf4
color12 #8aadf4

# magenta
color5  #f5bde6
color13 #f5bde6

# cyan
color6  #8bd5ca
color14 #8bd5ca

# white
color7  #b8c0e0
color15 #b8c0e0

# Padding
window_padding_width 10
