# Auto-gerado a partir do tema Omarchy
# Baseado em: alacritty.toml

# Cores básicas
foreground              #d8dee9
background              #2e3440
background_opacity      0.9
selection_foreground    #2e3440
selection_background    #d8dee9

# Cores do cursor
cursor                  #d8dee9
cursor_text_color       #2e3440

# Cor do link URL
url_color               #81a1c1

# Cores das bordas
active_border_color     #81a1c1
inactive_border_color   #3b4252
bell_border_color       #ebcb8b

# Cores das abas
active_tab_foreground   #2e3440
active_tab_background   #81a1c1
inactive_tab_foreground #d8dee9
inactive_tab_background #3b4252
tab_bar_background      #2e3440

# As 16 cores do terminal
# black
color0 #3b4252
color8 #3b4252

# red
color1 #bf616a
color9 #bf616a

# green
color2  #a3be8c
color10 #a3be8c

# yellow
color3  #ebcb8b
color11 #ebcb8b

# blue
color4  #81a1c1
color12 #81a1c1

# magenta
color5  #b48ead
color13 #b48ead

# cyan
color6  #88c0d0
color14 #88c0d0

# white
color7  #e5e9f0
color15 #e5e9f0

# Padding
window_padding_width 10
