# Auto-gerado a partir do tema Omarchy
# Baseado em: alacritty.toml

# Cores básicas
foreground              #4c4f69
background              #eff1f5
background_opacity      0.9
selection_foreground    #eff1f5
selection_background    #4c4f69

# Cores do cursor
cursor                  #4c4f69
cursor_text_color       #eff1f5

# Cor do link URL
url_color               #1e66f5

# Cores das bordas
active_border_color     #1e66f5
inactive_border_color   #bcc0cc
bell_border_color       #df8e1d

# Cores das abas
active_tab_foreground   #eff1f5
active_tab_background   #1e66f5
inactive_tab_foreground #4c4f69
inactive_tab_background #bcc0cc
tab_bar_background      #eff1f5

# As 16 cores do terminal
# black
color0 #bcc0cc
color8 #bcc0cc

# red
color1 #d20f39
color9 #d20f39

# green
color2  #40a02b
color10 #40a02b

# yellow
color3  #df8e1d
color11 #df8e1d

# blue
color4  #1e66f5
color12 #1e66f5

# magenta
color5  #ea76cb
color13 #ea76cb

# cyan
color6  #179299
color14 #179299

# white
color7  #5c5f77
color15 #5c5f77

# Padding
window_padding_width 10
