# Auto-gerado a partir do tema Omarchy
# Baseado em: alacritty.toml

# Cores básicas
foreground              #dcd7ba
background              #1f1f28
background_opacity      0.9
selection_foreground    #1f1f28
selection_background    #dcd7ba

# Cores do cursor
cursor                  #dcd7ba
cursor_text_color       #1f1f28

# Cor do link URL
url_color               #7e9cd8

# Cores das bordas
active_border_color     #7e9cd8
inactive_border_color   #090618
bell_border_color       #c0a36e

# Cores das abas
active_tab_foreground   #1f1f28
active_tab_background   #7e9cd8
inactive_tab_foreground #dcd7ba
inactive_tab_background #090618
tab_bar_background      #1f1f28

# As 16 cores do terminal
# black
color0 #090618
color8 #090618

# red
color1 #c34043
color9 #c34043

# green
color2  #76946a
color10 #76946a

# yellow
color3  #c0a36e
color11 #c0a36e

# blue
color4  #7e9cd8
color12 #7e9cd8

# magenta
color5  #957fb8
color13 #957fb8

# cyan
color6  #6a9589
color14 #6a9589

# white
color7  #c8c093
color15 #c8c093

# Padding
window_padding_width 10
