# Auto-gerado a partir do tema Omarchy
# Baseado em: alacritty.toml

# Cores básicas
foreground              #bebebe
background              #121212
background_opacity      0.9
selection_foreground    #121212
selection_background    #bebebe

# Cores do cursor
cursor                  #bebebe
cursor_text_color       #121212

# Cor do link URL
url_color               #e68e0d

# Cores das bordas
active_border_color     #e68e0d
inactive_border_color   #333333
bell_border_color       #b91c1c

# Cores das abas
active_tab_foreground   #121212
active_tab_background   #e68e0d
inactive_tab_foreground #bebebe
inactive_tab_background #333333
tab_bar_background      #121212

# As 16 cores do terminal
# black
color0 #333333
color8 #333333

# red
color1 #D35F5F
color9 #D35F5F

# green
color2  #FFC107
color10 #FFC107

# yellow
color3  #b91c1c
color11 #b91c1c

# blue
color4  #e68e0d
color12 #e68e0d

# magenta
color5  #D35F5F
color13 #D35F5F

# cyan
color6  #bebebe
color14 #bebebe

# white
color7  #bebebe
color15 #bebebe

# Padding
window_padding_width 10
