# Auto-gerado a partir do tema Omarchy
# Baseado em: alacritty.toml

# Cores básicas
foreground              #C1C497
background              #111c18
background_opacity      0.9
selection_foreground    #111c18
selection_background    #C1C497

# Cores do cursor
cursor                  #C1C497
cursor_text_color       #111c18

# Cor do link URL
url_color               #509475

# Cores das bordas
active_border_color     #509475
inactive_border_color   #23372B
bell_border_color       #459451

# Cores das abas
active_tab_foreground   #111c18
active_tab_background   #509475
inactive_tab_foreground #C1C497
inactive_tab_background #23372B
tab_bar_background      #111c18

# As 16 cores do terminal
# black
color0 #23372B
color8 #23372B

# red
color1 #FF5345
color9 #FF5345

# green
color2  #549e6a
color10 #549e6a

# yellow
color3  #459451
color11 #459451

# blue
color4  #509475
color12 #509475

# magenta
color5  #D2689C
color13 #D2689C

# cyan
color6  #2DD5B7
color14 #2DD5B7

# white
color7  #F6F5DD
color15 #F6F5DD

# Padding
window_padding_width 10
