# Auto-gerado a partir do tema Omarchy
# Baseado em: alacritty.toml

# Cores básicas
foreground              foreground = '#a9b1d6'
background              background = '#1a1b26'
background_opacity      0.9
selection_foreground    background = '#1a1b26'
selection_background    foreground = '#a9b1d6'

# Cores do cursor
cursor                  foreground = '#a9b1d6'
cursor_text_color       background = '#1a1b26'

# Cor do link URL
url_color               blue = '#7aa2f7'

# Cores das bordas
active_border_color     blue = '#7aa2f7'
inactive_border_color   black = '#32344a'
bell_border_color       yellow = '#e0af68'

# Cores das abas
active_tab_foreground   background = '#1a1b26'
active_tab_background   blue = '#7aa2f7'
inactive_tab_foreground foreground = '#a9b1d6'
inactive_tab_background black = '#32344a'
tab_bar_background      background = '#1a1b26'

# As 16 cores do terminal
# black
color0 black = '#32344a'
color8 black = '#32344a'

# red
color1 red = '#f7768e'
color9 red = '#f7768e'

# green
color2  green = '#9ece6a'
color10 green = '#9ece6a'

# yellow
color3  yellow = '#e0af68'
color11 yellow = '#e0af68'

# blue
color4  blue = '#7aa2f7'
color12 blue = '#7aa2f7'

# magenta
color5  magenta = '#ad8ee6'
color13 magenta = '#ad8ee6'

# cyan
color6  cyan = '#449dab'
color14 cyan = '#449dab'

# white
color7  white = '#787c99'
color15 white = '#787c99'

# Padding
window_padding_width 10
