[screencast]
# Usar implementação do hyprland para screencast
chooser_type=simple
exec_before=
exec_after=
# Excluir workspaces especiais da captura
exclude_workspaces=special:scratchpad,special:hidden,special:slack
# Resolução máxima
max_fps=60
force_mod_linear=true
